version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-datos:
    build:
      context: ./ms-datos
      dockerfile: Dockerfile
    container_name: ms-datos
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/ms_datos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db_postgres:
        condition: service_healthy

  ms-kpis:
    build:
      context: ./ms-kpis
      dockerfile: Dockerfile
    container_name: ms-kpis
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/ms_datos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db_postgres:
        condition: service_healthy

  ms-reportes:
    build:
      context: ./ms-reportes
      dockerfile: Dockerfile
    container_name: ms-reportes
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/ms_reportes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db_postgres:
        condition: service_healthy

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/ms_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db_postgres:
        condition: service_healthy

volumes:
  postgres_data:
